#suppress inspection "UnusedProperty" for whole file
.blurb=Search the academy
.longName=Summoners Chapter 1 Keystone
.name=Event
~01~~panel_001~1_hero=It's just like at <town>. Gorgons and thrixl and the rest all together.
~01~~panel_002~2_hero2=No sign of <legend> or the others, though.
~01~~panel_002~4_hero3=Library walls are intact.
~01~~panel_003~1_hero=They're swarming the main entrance on the east. We should go for the south garden entrance.
~01~~panel_003~2_hero2=The garden? You mean the hedge maze?
~01~~panel_004~1_hero=Right. Anyone remember what the lockword was going to be this <season>?
~01~~panel_005~2_hero2=(something based on legend's personality; make sure it's one of the starting 3 that says it)
~01~~panel_005~3_hero4=Lockword?
