#suppress inspection "UnusedProperty" for whole file
.blurb=villain_summoners
.longName=villain_summoners
.name=Event
~01~prompt~panel_001~1_leader=<leader.personality:How strange.../Is that the last of them?/Anyone else see the dart riding a roe?/Are there any left?/Is everyone okay?/Anyone left?/Are we all clear?/Is that all of them/Is that all of them?/Is that the last of them?/Did we get them all?>
~01~prompt~panel_002~1_target2=I think it's time.
~01~prompt~panel_003~1_leader=Time?
~01~prompt~panel_004~1_target2=To choose a name. We never did back then.
~01~prompt~panel_005~1_narration=Every company of heroes is called by at least one name.
~01~prompt~panel_005~2_narration=A name spoken or spelled in tradition, \nand handed along ever after.
~01~prompt~panel_005~4_narration=These heroes will be known as...
~02~choice_one~panel_001~1_narration=<nameSuggestion.1>!
~03~choice_two~panel_001~1_narration=<nameSuggestion.2>!
~04~choice_three~panel_001~1_narration=<nameSuggestion.3>!
~05~choice_four~panel_001~1_leader=[i][gray]Enter your own name.[]
~05~choice_four~panel_001~2_narration=. . . ?
~06~~panel_001~1_action=Here follow the tales of:\n<company>
